
import java.awt.Point;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Matthew
 */
public class GridDebugFrame extends javax.swing.JFrame {
    Map map = new Map(4, 4);
    /**
     * Creates new form testFrame
     */
    public GridDebugFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gridPane1 = new GridPane();
        buttonRightUp = new javax.swing.JButton();
        buttonLeftUp = new javax.swing.JButton();
        buttonLeftDown = new javax.swing.JButton();
        buttonRightDown = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        buttonDrawCircle = new javax.swing.JButton();
        textX = new javax.swing.JTextField();
        textY = new javax.swing.JTextField();
        buttonClear = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuReturn = new javax.swing.JMenu();
        menuItemReturn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grid debug window");

        gridPane1.setColumns(6);

        javax.swing.GroupLayout gridPane1Layout = new javax.swing.GroupLayout(gridPane1);
        gridPane1.setLayout(gridPane1Layout);
        gridPane1Layout.setHorizontalGroup(
            gridPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        gridPane1Layout.setVerticalGroup(
            gridPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        buttonRightUp.setText("draw route right up");
        buttonRightUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRightUpActionPerformed(evt);
            }
        });

        buttonLeftUp.setText("draw route left up");
        buttonLeftUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLeftUpActionPerformed(evt);
            }
        });

        buttonLeftDown.setText("draw route left down");
        buttonLeftDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLeftDownActionPerformed(evt);
            }
        });

        buttonRightDown.setText("draw route right down");
        buttonRightDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRightDownActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter number of columns (and press enter)");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        buttonDrawCircle.setText("draw circle at these coordinates:");
        buttonDrawCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDrawCircleActionPerformed(evt);
            }
        });

        buttonClear.setText("Clear drawn contents from grid");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        menuReturn.setText("Debug menu");

        menuItemReturn.setText("Return to navigation screen");
        menuItemReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReturnActionPerformed(evt);
            }
        });
        menuReturn.add(menuItemReturn);

        jMenuBar1.add(menuReturn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(69, 69, 69))
                    .addComponent(buttonClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gridPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonLeftDown)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonRightDown))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonLeftUp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonRightUp))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonDrawCircle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textX, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textY, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonLeftDown, buttonLeftUp, buttonRightDown, buttonRightUp});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gridPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLeftUp)
                    .addComponent(buttonRightUp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLeftDown)
                    .addComponent(buttonRightDown))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDrawCircle)
                    .addComponent(textY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonClear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRightUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRightUpActionPerformed
        gridPane1.clearLines();
        ArrayList<Point> routePoints = map.getRouteToPoint(new Point(6,2));
        
        System.out.println(routePoints);
        
        gridPane1.addRouteOnGrid(routePoints);
    }//GEN-LAST:event_buttonRightUpActionPerformed

    private void buttonLeftUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLeftUpActionPerformed
        gridPane1.clearLines();
        ArrayList<Point> routePoints = map.getRouteToPoint(new Point(2,2));
        
        System.out.println(routePoints);
        
        gridPane1.addRouteOnGrid(routePoints);
    }//GEN-LAST:event_buttonLeftUpActionPerformed

    private void buttonLeftDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLeftDownActionPerformed
        gridPane1.clearLines();
        ArrayList<Point> routePoints = map.getRouteToPoint(new Point(2,6));
        
        System.out.println(routePoints);
        
        gridPane1.addRouteOnGrid(routePoints);
    }//GEN-LAST:event_buttonLeftDownActionPerformed

    private void buttonRightDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRightDownActionPerformed
        gridPane1.clearLines();
        ArrayList<Point> routePoints = map.getRouteToPoint(new Point(6,6));
        
        System.out.println(routePoints);
        
        gridPane1.addRouteOnGrid(routePoints);
    }//GEN-LAST:event_buttonRightDownActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        gridPane1.setColumns(Integer.parseInt(jTextField1.getText()));
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void buttonDrawCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDrawCircleActionPerformed
        gridPane1.addCircleOnGrid(Integer.parseInt(textX.getText()), Integer.parseInt(textY.getText()));
    }//GEN-LAST:event_buttonDrawCircleActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        gridPane1.clearCircles();
        gridPane1.clearLines();
    }//GEN-LAST:event_buttonClearActionPerformed

    private void menuItemReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReturnActionPerformed
        MapWindow.main(new String[0]);
        dispose();
    }//GEN-LAST:event_menuItemReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GridDebugFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GridDebugFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GridDebugFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GridDebugFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GridDebugFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDrawCircle;
    private javax.swing.JButton buttonLeftDown;
    private javax.swing.JButton buttonLeftUp;
    private javax.swing.JButton buttonRightDown;
    private javax.swing.JButton buttonRightUp;
    private GridPane gridPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem menuItemReturn;
    private javax.swing.JMenu menuReturn;
    private javax.swing.JTextField textX;
    private javax.swing.JTextField textY;
    // End of variables declaration//GEN-END:variables
}
