import java.awt.Color;
import java.awt.Point;
import java.util.ArrayList;
import javafx.scene.shape.Line;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Matthew
 */
public class MapWindow extends javax.swing.JFrame {
    Map map = new Map();
    
    private Point originPoint = map.getOriginPoint();
    
    private ArrayList<Store> storeArray = map.getClosenessSortedStores();
    private ArrayList<Point> storeCoords = new ArrayList<>();
    
    /**
     * Creates new form MapWindow
     */
    public MapWindow() {
        initComponents();
        addStores();
        addUser();
        genText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        gridPane1 = new GridPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        textStores = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        textStoreCoords = new javax.swing.JTextArea();
        comboRoute = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textStoreDistance = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOptions = new javax.swing.JMenu();
        menuItemBack = new javax.swing.JMenuItem();
        menuItemDebugMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mapping");

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jTextPane1.setText("Based on the location you provided, these are the closest stores to you.");
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setEditable(false);
        jTextPane2.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jTextPane2.setText("They should  contain all items requested.");
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout gridPane1Layout = new javax.swing.GroupLayout(gridPane1);
        gridPane1.setLayout(gridPane1Layout);
        gridPane1Layout.setHorizontalGroup(
            gridPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        gridPane1Layout.setVerticalGroup(
            gridPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        textStores.setEditable(false);
        textStores.setColumns(20);
        textStores.setLineWrap(true);
        textStores.setRows(5);
        jScrollPane3.setViewportView(textStores);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        textStoreCoords.setEditable(false);
        textStoreCoords.setColumns(20);
        textStoreCoords.setLineWrap(true);
        textStoreCoords.setRows(5);
        jScrollPane4.setViewportView(textStoreCoords);

        comboRoute.setAutoscrolls(true);
        comboRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRouteActionPerformed(evt);
            }
        });

        jLabel1.setText("Show route to:");

        textStoreDistance.setEditable(false);
        textStoreDistance.setColumns(20);
        textStoreDistance.setLineWrap(true);
        textStoreDistance.setRows(5);
        jScrollPane5.setViewportView(textStoreDistance);

        menuOptions.setText("Options");

        menuItemBack.setText("Go back to item selection");
        menuItemBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBackActionPerformed(evt);
            }
        });
        menuOptions.add(menuItemBack);

        menuItemDebugMenu.setText("Grid debug menu");
        menuItemDebugMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDebugMenuActionPerformed(evt);
            }
        });
        menuOptions.add(menuItemDebugMenu);

        jMenuBar1.add(menuOptions);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gridPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane3)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(gridPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2)))
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addStores() {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                for (Store store : storeArray) {
                    gridPane1.addCircleOnGrid(store.getX(), store.getY(), Color.GRAY, false);
                }
            }
        });
    }
    
    private void addUser() {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                gridPane1.addCircleOnGrid(map.getOriginPoint(), Color.WHITE, false);
            }
        });
    }
    
    private void genText() {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                String allStoreNames = "", allStoreCoords = "", allStoreDistances = "";
                int i = 0;
                
                for (Store store : storeArray) {
                    allStoreNames += ("(" + i + ")   " + store.getStoreName() + "\n");
                    allStoreCoords += (store.getPointString() + "\n");
                    allStoreDistances += ((Math.round(map.distanceToStore(store) * 100.0) / 100.0) + "km\n");

                    storeCoords.add(store.getPoint());

                    comboRoute.addItem("(" + i + ")   " + store.getStoreName());
                    
                    i++;
                }

                textStores.setText(allStoreNames);
                textStoreCoords.setText(allStoreCoords);
                textStoreDistance.setText(allStoreDistances);
            }
        });
    }
    
    private void menuItemBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBackActionPerformed
        LocatorWindow.main(new String[0]);
        dispose();
    }//GEN-LAST:event_menuItemBackActionPerformed

    private void menuItemDebugMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDebugMenuActionPerformed
        GridDebugFrame.main(new String[0]);
        dispose();
    }//GEN-LAST:event_menuItemDebugMenuActionPerformed

    private void comboRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRouteActionPerformed
        Store store = map.getStoreAt(storeCoords.get(comboRoute.getSelectedIndex()));
        
        gridPane1.clearLines();
        gridPane1.addRouteOnGrid(map.getRouteToPoint(store.getPoint()), Color.RED);
    }//GEN-LAST:event_comboRouteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboRoute;
    private GridPane gridPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JMenuItem menuItemBack;
    private javax.swing.JMenuItem menuItemDebugMenu;
    private javax.swing.JMenu menuOptions;
    private javax.swing.JTextArea textStoreCoords;
    private javax.swing.JTextArea textStoreDistance;
    private javax.swing.JTextArea textStores;
    // End of variables declaration//GEN-END:variables
}
